exclude: [config.rb, sass, Gruntfile.js, node_modules, Makefile, package.json, svg]
safe: true
lsi: false
name: JSconf.eu
url:  https://2017.jsconf.eu
twitter_username: jsconfeu
baseurl:

speaker_map_base_url: "https://maps.googleapis.com/maps/api/staticmap?style=hue:0xfe006b&amp;size=640x163&amp;scale=2&amp;sensor=false&amp;zoom=5&amp;visual_refresh=1&amp;markers=color:"
speaker_index_base_url: "https://maps.googleapis.com/maps/api/staticmap?style=hue:0xfe006b&amp;size=514x324&amp;sensor=false&amp;visual_refresh=1&amp;markers=color:"
news_map_base_url: "https://maps.googleapis.com/maps/api/staticmap?size=640x390&amp;sensor=false&amp;visual_refresh=1&amp;markers=color:"
schedule_url: "https://docs.google.com/spreadsheet/pub?key=0AoIOxKkr6fGqdGtHdWJqZFBJUnF1bEt3RVBsQUxINVE&amp;single=true&amp;gid=1&amp;output=html"

permalink: pretty
